route:
  receiver: 'proxy'
  group_wait: 1s
  group_interval: 10s
  repeat_interval: 10s

receivers:
  - name: 'proxy'
    webhook_configs:
      - url: 'http://scaler-proxy:9245/delegate'
        send_resolved: false