global:
  scrape_interval: 1s
  scrape_timeout: 1s
  evaluation_interval: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - 'activemq:8080'
  - job_name: spring-actuator
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 'scaler-proxy:9245'
          - 'consumer-persistence:8965'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
